# Define variables

$names = @("Red","Green","Blue","Router")
$vhdPath = "C:\VM"
# Create virtual machine
foreach($name in $names){

$path = $vhdPath+"\$name\$name"+".vhdx"

Remove-VM -Name $name -Force
Remove-Item $path

}

# SIG # Begin signature block
# MIIFfwYJKoZIhvcNAQcCoIIFcDCCBWwCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU8M29zLm6RQtV46ACK3imUB3E
# eMegggMUMIIDEDCCAfigAwIBAgIQGgxxhSY8Z7ZFVSS1V899ODANBgkqhkiG9w0B
# AQUFADAgMR4wHAYDVQQDDBVDaGlsbCBWaWJlcyBUZWNoIExhYnMwHhcNMjUwNTMx
# MTUzNTA1WhcNMjYwNTMxMTU1NTA1WjAgMR4wHAYDVQQDDBVDaGlsbCBWaWJlcyBU
# ZWNoIExhYnMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYmOfM43EX
# ggrVcWcNrEckunO0033WLsJD85AhOUgPltRGsicHBx9ebFVii07oGpAqmIeWPdrs
# 8Kxc+CsIwaXa2Mt6Mm+zcdYgTOee0zSmzXe1L1fFaBlihUK6oob5AZ7GsFU6fgPu
# MBYbtUHrcjyfUTE/4aR2fM0iOHFbDlI+BSecUiVAm7LHkDWh3QwyFzI0uz1FRzaV
# wHIWz5887aVYwNWeLNUToAjMZWWjoOxZ+7FCZ9NpVpVTlsiwbEkrgauSM3ndvhtI
# kGf0uWS4dfk6Q3J2dy9Ygryq1b4TnrGJ+0EGI1UHdS5KMJyrgFKc8sFXdeCsDWj5
# eYEq59U+1n9tAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzAdBgNVHQ4EFgQUyGSkoKHGXemOO/R1Q3xMQkO0HqgwDQYJKoZIhvcN
# AQEFBQADggEBAFvx8k8jXbSe0uSiAPP3waqu418iZhRPPaKTz9Ublt0TT9hYykw5
# LbukUj7beCtkhP+l04TKzTrrmdLjYTAelhX0tLwEDRPCi8GLkjuUkOIyWFHfImOV
# P3hw1hif3j1Bx98sXdsXitDLaQY+P7vUOTWqucvg673e1T12f6h9SW1DS1J5B3Jk
# VUDQOebd5G8/x//V/hlJkjFNEw7QRmD+TS48W41JmznL35zucNPDlSvKrCkItaez
# lmbh6PMlieEwZ84rQBTeZ4cJyBQHsfrmS3cAih93kICvWxgZI/ovwS4b1qTzsXlE
# yEBiUmG/Kdhv4ElaN2xTUMbHlYR3pCybUu0xggHVMIIB0QIBATA0MCAxHjAcBgNV
# BAMMFUNoaWxsIFZpYmVzIFRlY2ggTGFicwIQGgxxhSY8Z7ZFVSS1V899ODAJBgUr
# DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMx
# DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkq
# hkiG9w0BCQQxFgQU1oZwcZsryFbiQT6Zn40ip2IBbmAwDQYJKoZIhvcNAQEBBQAE
# ggEAYugidX/2OqIdm5pm/PcMq8thML9gEufIX4sNjjSkwGdl8OvmRK4PtdrKDUu6
# hJGJim8JzSs7LQ5yCqxu6CVyKZfLl6Kb7VlmXzETHbeEpGMhDmF7FcvfryUYSHjC
# Hi7rc5lG7o1olqQ1T6pqS7mNobydTleGoSuXze76hGtC+vq/76i0Ai9WDrqFs1iq
# mVBYwj09E4nVPM/DcbylnKIZPwwC+QIi+ASSPRfnzSZf2j2RbjyvuX6GQPE3KNh1
# A169lHW1YScOVp+oBIOmEQrS1KilLit69BLtYyTbA7mqJCzoo/Da0ACxCzrh/FuI
# oYdw6ArtO/yzj3UrWI67FPCV3A==
# SIG # End signature block
